---
- name: Install MySQL
  yum:
    name:
      - mariadb
      - mariadb-server
      - MySQL-python
    state: present
  notify: Start and enable MySQL
 
- name: Start and enable MySQL
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
  no_log: True

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "webapp_user"
    login_password: "secure_password"
 
